import { IConfig } from '../../../src/models/SidiModel';
import { commonConfig, flutterConfig, qualityConfig, rnConfig } from '../configs';

const config: IConfig = {
  mandatoryKeys: [],
  conditionalSteps: [...commonConfig, ...rnConfig, ...flutterConfig, ...qualityConfig],
  stepsFamily: [
    '_react_native_pre_build',
    '_flutter_pre_build',
    '_npm_private_login',
    '_react_native_yarn_install',
    '_react_native_lint',
    '_react_native_tsc',
    '_react_native_prettier',
    '_react_native_jest',
    '_react_native_npm_install',
    '_react_native_npm_lint',
    '_react_native_npm_tsc',
    '_react_native_npm_prettier',
    '_react_native_npm_jest',
    '_react_native_npm_library_install',
    '_react_native_yarn_library_install',
    '_flutter_yarn_install',
    '_flutter_jest',
    '_flutter_lint',
    '_flutter_prettier',
    '_audit_packages_yarn',
    '_audit_packages_outdated',
    '_audit_packages_urls',
    '_audit_packages_third_parties',
    '_audit_export_report',
    '_audit_app_mobsf',
    '_audit_app_decompile',
    '_audit_app_permissions',
    '_audit_app_sizes',
    '_audit_app_logs',
    '_deploy_to_cicd',
    '_audit_conditional_fail',
    '_send_slack_message',
    '_send_teams_message',
    '_gitlab_status_ending',
    '_github_status_ending',
  ],
  publishingSteps: ['_gitlab_status_ending_failure', '_github_status_ending_failure'],
};

export default config;
