name: "[PRE] - Check VERSIONED BRANCHES"
script: |
  #!/bin/bash
  GIT_BRANCH=${CM_BRANCH}
  
  echo "GIT_BRANCH: $GIT_BRANCH"
  

  if [[ ${GIT_BRANCH} =~ ^[A-Za-z]+\/([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
      echo "xxx/X.Y.Z branch mode"
      # get version from branch
      APP_VERSION="${BASH_REMATCH[1]}"
      INCREMENT_VERSION="1"
  
      if [ "$APP_VERSION" == "" ]
      then
          APP_VERSION="0.0.0"
      fi
  
      echo "BRANCH_TYPE=$BRANCH_TYPE" >> $CM_ENV
      echo "APP_VERSION=$APP_VERSION" >> $CM_ENV
      echo "INCREMENT_VERSION=$INCREMENT_VERSION" >> $CM_ENV
  else
      echo "Other branch mode, branch has to respect this format: xxx/X.Y.Z\n Where X.Y.Z correspond to your version"
      APP_VERSION="0.0.0"
  
      echo "APP_VERSION=$APP_VERSION" >> $CM_ENV
  fi