name: "[ANDROID] - Building the app (AAB)"
script: |
  #!/bin/sh
  set -ex
  
  cd $GRADLEW_PATH
  chmod 777 gradlew
  
  if [[ ${AAB_SPECIFIC_BUILD_VARIANT} == "" ]]; then
    ./gradlew "bundle$AAB_SPECIFIC_BUILD_VARIANT"
  else
    ./gradlew "bundle$ANDROID_BUILD_VARIANT"
  fi