name: "[PRE] - GitLab status - Success job"
script: |
  #!/usr/bin/env bash
  set -ex
  
  SEND_SUCCESS_STATUS=$(curl -H "Content-Type: application/json" -H "Authorization: Bearer $GITLAB_TOKEN" --data "{\"state\": \"success\",\"target_url\": \"https://codemagic.io/app/$CM_PROJECT_ID/build/$CM_BUILD_ID\",\"name\": \"ci/codemagic/$WORKFLOW\"}"  -X POST "https://gitlab.com/api/v4/projects/$GITLAB_REPOSITORY_ID/statuses/$CM_COMMIT")

  BUILD_STATUS="success"
  echo "BUILD_STATUS=$BUILD_STATUS" >> $CM_ENV