name: "[END-TO-END] end_to_end build launcher"
script: |
  #!/usr/bin/env bash
  # fail if any commands fails
  set -ex

  # Check if IOS_BUILD_SLUG_1 is defined and not "EMPTY"
  if [[ -n "$IOS_BUILD_SLUG_1" && "$IOS_BUILD_SLUG_1" != "EMPTY" ]]; then
      # Trigger a build using Codemagic API
      curl -H "Content-Type: application/json" \
          -H "x-auth-token: $CODE_MAGIC_TOKEN" \
          --data "{
              \"appId\": \"$CM_PROJECT_ID\",
              \"workflowId\": \"$WORKFLOW\",
              \"branch\": \"$CM_BRANCH\",
              \"environment\": {
                  \"variables\": {
                      \"END_TO_END_BUILD_LIST\": \"$END_TO_END_BUILD_LIST\",
                      \"END_TO_END_BUILD_LIST_INDEX\": \"$END_TO_END_BUILD_LIST_INDEX\",
                      \"RETRIGGER_WAITING_PREVIOUS_BUILDS\": \"$RETRIGGER_WAITING_PREVIOUS_BUILDS\",
                      \"WDIO_CONFIG_PATH_ANDROID\": \"$WDIO_CONFIG_PATH_ANDROID\",
                      \"IOS_BUILD_SLUG_1\": \"$IOS_BUILD_SLUG_1\",
                      \"IOS_BUILD_SLUG_2\": \"$IOS_BUILD_SLUG_2\",
                      \"IOS_BUILD_SLUG_3\": \"$IOS_BUILD_SLUG_3\",
                      \"ANDROID_BUILD_SLUG_1\": \"$ANDROID_BUILD_SLUG_1\",
                      \"ANDROID_BUILD_SLUG_2\": \"$ANDROID_BUILD_SLUG_2\",
                      \"ANDROID_BUILD_SLUG_3\": \"$ANDROID_BUILD_SLUG_3\"
                  }
              }
          }" https://api.codemagic.io/builds
      echo "✅ Build has been triggered"
  else
      echo "❎ IOS_BUILD_SLUG_1 is not set or is 'EMPTY'. Skipping build trigger."
  fi
