name: "[ANDROID] - Building the app (APK)"
script: |
  #!/bin/sh
  set -ex
  
  cd $GRADLEW_PATH
  chmod 777 gradlew
  
  ./gradlew "assemble${ANDROID_BUILD_VARIANT}Release" -Dorg.gradle.jvmargs="-Xmx4096m"
