name: "[PROMOTE] - Promote app"
script: |
  #!/bin/sh
  set -ex
  
  npm i -g devops-helper
  if [[ "$INCREMENT_VERSION" != "" ]]; then
    devops-helper promote-app $REPOSITORY_URL $BRANCHES $APP_VERSION
  else
    if [ ${IS_VERSIONED_BRANCH} == "true" ]; then
      devops-helper promote-app $REPOSITORY_URL $BRANCHES $APP_VERSION
    else
      devops-helper promote-app $REPOSITORY_URL $BRANCHES --noVersionedBranch
    fi
  fi