name: "[PROMOTE] - Promote app"
script: |
  #!/bin/sh
  set -ex
  
  if [[ "$INCREMENT_VERSION" != "" ]]; then
    npx --yes devops-helper promote-app $REPOSITORY_URL $BRANCHES $APP_VERSION
  else
    if [ ${IS_VERSIONED_BRANCH} == "true" ]; then
      npx --yes devops-helper promote-app $REPOSITORY_URL $BRANCHES $APP_VERSION
    else
      npx --yes devops-helper promote-app $REPOSITORY_URL $BRANCHES --noVersionedBranch
    fi
  fi