name: "[PRE] - Pre build steps"
script: |
  #!/usr/bin/env bash
  set -ex

  echo "[REACT-NATIVE] - Install ReactNative cli"
  echo "Available react-native-cli versions: $(npm view react-native-cli versions)"

  yarn global add react-native-cli

  echo "PATH=$PATH" >> $CM_ENV
  
  # Install NVM
  PROFILE=$HOME/.profile
  touch $PROFILE
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | PROFILE=$PROFILE bash
  source $PROFILE
  
  if [ ! -z "${CM_BUILD_DIR}" ] ; then
    echo "Switching to working directory: ${CM_BUILD_DIR}"
  
    cd "${CM_BUILD_DIR}"
    if [ $? -ne 0 ] ; then
    echo "Failed to switch to working directory: ${CM_BUILD_DIR}"
    fi
  fi
  
  # Install latest node version by default
  if [[ -z "$NODE_VERSION" && ! -e "./.nvmrc" ]]; then NODE_VERSION="node"; fi
  
  nvm install ${NODE_VERSION}
  
  echo "PATH=$PATH" >> $CM_ENV
