name: "[ANDROID] - Set version code manifest"
script: |
  #!/bin/sh
  set -ex
  
  # Code from https://github.com/jamesmontemagno/steps-set-android-manifest-versions/blob/master/step.sh
  
  manifest_file_path="$TARGET_ANDROID/src/main/AndroidManifest.xml"
  new_version_code="$PROJECT_BUILD_NUMBER"
  new_version_name="$APP_VERSION"
  
  if [ ! -f "${manifest_file_path}" ] ; then
    echo " [!] File doesn't exist at specified AndroidManifest.xml path: ${manifest_file_path}"
    exit 1
  fi
  
  echo " (i) Provided Android Manifest path: ${manifest_file_path}"
  echo " (i) Version Code: ${new_version_code}"
  echo " (i) Version Name: ${new_version_name}"
  
  VERSIONCODE=`grep versionCode ${manifest_file_path} | sed 's/.*versionCode="//;s/".*//'`
  VERSIONNAME=`grep versionName ${manifest_file_path} | sed 's/.*versionName\s*=\s*\"\([^\"]*\)\".*/\1/g'`
  
  if [ -z "${VERSIONCODE}" ] ; then
    echo " [!] Could not find current Version Code!"
    exit 1
  fi

  echo "Version code detected: ${VERSIONCODE}"
  if [ ! -z "${version_code_offset}" ] ; then
    echo " (i) Version code offset: ${version_code_offset}"

    CONFIG_new_version_code=$((${new_version_code} + ${version_code_offset}))
  else
    CONFIG_new_version_code=${new_version_code}
  fi
  
  echo " (i) Version code: ${CONFIG_new_version_code}"
  
  if [ -z "${VERSIONNAME}" ] ; then
    echo " [!] Could not find current Version Name!"
    exit 1
  fi
  echo "Version name detected: ${VERSIONNAME}"
  
  # ---------------------
  # --- Main:

  # verbose / debug print commands

  set -v
  # ---- Set Build Version Code:

  sed -i.bak "s/android:versionCode="\"${VERSIONCODE}\""/android:versionCode="\"${CONFIG_new_version_code}\""/" ${manifest_file_path}

  # ---- Set Build Version Code if it was specified:
  if ! [ -z "${new_version_name}" ] ; then
    sed -i.bak "s/android:versionName="\"${VERSIONNAME}\""/android:versionName="\"${new_version_name}\""/" ${manifest_file_path}
  fi


  # ---- Remove backup:

  rm -f ${manifest_file_path}.bak

  # ==> Build Version changed