name: "[AUDIT] - Fail on high/critical vulnerabilities"
ignore_failure: true
script: |
   #!/bin/sh
   set -ex
   
   # export vulnerability count for further use
   if [[ ${CRITICAL_COUNT} != "0" || ${HIGH_COUNT} != "0"  ]]; then
    echo "/!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\\"
    echo "/!\ /!\ /!\ You have critical/high vulnerabilities ! Fix them ASAP ! /!\ /!\ /!\\"
    echo "/!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\\"
    exit 1
   fi