name: "[PRE] - GitHub status - Update build status"
script: |
  #!/usr/bin/env bash
  set -ex

  SEND_RUNNING_STATUS=$(curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $GITHUB_TOKEN" "$REPOSITORY_URL/statuses/$CM_COMMIT" --data "{\"state\": \"pending\",\"target_url\": \"https://codemagic.io/app/$CM_PROJECT_ID/build/$CM_BUILD_ID\",\"description\": \"ci/codemagic/$WORKFLOW\"}")
  echo "SEND_RUNNING_STATUS: $SEND_RUNNING_STATUS"